name:                squid
version:             0.1.0.0
github:              "pkozakowski/squid"
license:             MIT
author:              "Piotr Kozakowski"
maintainer:          "piotr@kozakow.ski"
copyright:           "2021-2023 Piotr Kozakowski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pkozakowski/squid#readme>

dependencies:
- aeson
- aeson-pretty >= 0.8 && < 0.8.10
- AesonBson
- algebra
- approx
- base >=4.12 && <5
- bson
- bytestring
- composition
- constraints
- containers
- deepseq
- dhall
- directory
- either
- free
- hashable
- hashmap
- http-client
- hvega
- lazyio
- logging
- microlens
- mongoDB
- mtl
- optparse-applicative
- parallel
- parsec
- polysemy >= 1.6
- polysemy-plugin >= 0.3
- pretty-simple
- prettyprinter
- prettyprinter-ansi-terminal
- QuickCheck
- quickcheck-classes
- quickcheck-instances
- random
- req
- retry
- semigroupoids
- stm
- template-haskell
- tasty
- tasty-th
- tasty-quickcheck
- terminal-progress-bar
- text
- time
- vector

library:
  source-dirs: src

executables:
  squid-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -fplugin=Polysemy.Plugin
    - -flate-specialise
    - -fspecialise-aggressively
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - squid

tests:
  squid-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -fplugin=Polysemy.Plugin
    - -flate-specialise
    - -fspecialise-aggressively
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - squid

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DataKinds
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GADTs
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
