name:           approx
version:        0.1.0.1
description:    Please see the README on GitHub at <https://github.com/n-kishaloy/approx#readme>
homepage:       https://github.com/n-kishaloy/approx#readme
bug-reports:    https://github.com/n-kishaloy/approx/issues
author:         Kishaloy Neogi
maintainer:     nkishaloy@yahoo.com
copyright:      2020 Kishaloy Neogi
license:        MIT
license-file:   LICENSE
build-type:     Simple

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Easy-to-use reasonable way of emulating approximate in Haskell. 
category:            Numeric

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:         Please see the README on GitHub at <https://github.com/n-kishaloy/approx#readme>

dependencies:
  - base                      >= 4.7 && <5
  - containers                <= 0.6.4.1
  - hashable                  <= 1.3.0.0
  - text                      <= 1.2.4.1
  - time                      <= 1.11.1.1
  - unordered-containers      <= 0.2.13.0
  - vector                    <= 0.12.2.0

library:
  source-dirs: src

executables:
  approx-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - approx

tests:
  approx-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - approx
    - QuickCheck
