name:                example-erc20
version:             0.0.0.0
synopsis:            ERC20 token example.
github:              "airalab/hs-web3"
license:             Apache-2.0
author:              Aleksandr Krupenkin
maintainer:          mail@akru.me
copyright:           "(c) Aleksandr Krupenkin 2016-2021"
category:            Network

dependencies:
- base
- text
- web3
- microlens
- data-default
- web3-ethereum

executables:
  example-erc20:
    main:             Main.hs
    source-dirs:      ./
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
