Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://192.168.0.70:3000"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  port: 3334
  approot: "http://office.pfidev.jp/mpidl"
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
