name:                example-polkadot
version:             0.0.0.0
synopsis:            Polkadot API example.
github:              "airalab/hs-web3"
license:             Apache-2.0
author:              Aleksandr Krupenkin
maintainer:          mail@akru.me
copyright:           "(c) Aleksandr Krupenkin 2016-2021"
category:            Network

dependencies:
- base
- web3-provider
- web3-polkadot

executables:
  example-polkadot:
    main:             Main.hs
    source-dirs:      ./
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
